// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANsckky616vlZuM2pHMjfKkBZK9e9zFD8',
    appId: '1:477810502522:web:ceb87405543021886d04c3',
    messagingSenderId: '477810502522',
    projectId: 'fir-auth-example-d10e2',
    authDomain: 'fir-auth-example-d10e2.firebaseapp.com',
    storageBucket: 'fir-auth-example-d10e2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClCKWIx-AIsoQx208Gh8HQJo8osfUaxFE',
    appId: '1:477810502522:android:cdb294b0c358e5e36d04c3',
    messagingSenderId: '477810502522',
    projectId: 'fir-auth-example-d10e2',
    storageBucket: 'fir-auth-example-d10e2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEb8gyu5Y4k6cdsaiBMmxRgyTn-Jmm8uw',
    appId: '1:477810502522:ios:0377ec0a1685a6236d04c3',
    messagingSenderId: '477810502522',
    projectId: 'fir-auth-example-d10e2',
    storageBucket: 'fir-auth-example-d10e2.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEb8gyu5Y4k6cdsaiBMmxRgyTn-Jmm8uw',
    appId: '1:477810502522:ios:0377ec0a1685a6236d04c3',
    messagingSenderId: '477810502522',
    projectId: 'fir-auth-example-d10e2',
    storageBucket: 'fir-auth-example-d10e2.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthExample',
  );
}
